FROM debian:stable

RUN apt-get update && apt-get install -y \
	openresolv wireguard \
	curl \
	iproute2 \
	firefox-esr
	
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD chmod u+x /configFiles/startup.sh && bash /configFiles/startup.sh

# See startup.sh for commands that run when starting image
# wg-quick up mullvad-se5
# curl https://am.i.mullvad.net/connected
# firefox -headless https://twitch.tv
